name: Lib common - CI
on:
  schedule:
    - cron: '0 0 * * *' 
  push:
    branches:
      - 'main'
      - 'develop'
  workflow_dispatch:    
jobs:
  test-nightly:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build Maven
        run: mvn test -s .mvn/settings.xml 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  deploy-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: luiscajl/mvn-release@main
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          directory: ${{ env.DIRECTORY }}
      - uses: luiscajl/mvn-deploy@main
        with:
          directory: ${{ env.DIRECTORY }}
          github_workspace: $GITHUB_WORKSPACE
          github_token: ${{ secrets.GITHUB_TOKEN }} 
  next-snapshot:
    needs: deploy-release
    if: (github.ref == 'refs/heads/main')  && (github.event_name == 'push')  
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v2   
        with:
          ref: develop   
      - uses: luiscajl/next-maven-snapshot@main
  notification:
    needs: [deploy-release, next-snapshot, test-nightly]
    runs-on: ubuntu-latest  
    steps:     
    - name: Send telegram message
      if: ${{ failure() }}
      uses: xinthink/action-telegram@v1
      with:
        botToken: ${{ secrets.TELEGRAM_TOKEN }}
        chatId: ${{ secrets.TELEGRAM_TO }}
        jobStatus: ${{ job.status }}         
        