name: Lib common - CI
on:
  schedule:
    - cron: '0 0 * * *' 
  push:
    branches:
      - 'main'
      - 'develop'
  workflow_dispatch:    
jobs:
  test-nightly:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Build Maven
        run: mvn test -s .mvn/settings.xml 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  deploy-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: luiscajl/mvn-release@main
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          directory: ${{ env.DIRECTORY }}
      - uses: luiscajl/mvn-deploy@main
        with:
          directory: ${{ env.DIRECTORY }}
          github_workspace: $GITHUB_WORKSPACE
          github_token: ${{ secrets.GITHUB_TOKEN }} 
  pull-request:
    runs-on: ubuntu-latest
    needs: deploy-release
    if: (github.ref == 'refs/heads/develop')  && (github.event_name == 'push')  
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      id: open-pr
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}      
    - name: Send telegram message
      uses: appleboy/telegram-action@master
      if: ${{steps.open-pr.outputs.pr_url}}  
      with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            New pull-request: 
            
            Repository: ${{ github.repository }}

            See on: ${{steps.open-pr.outputs.pr_url}}             
  next-snapshot:
    needs: deploy-release
    if: (github.ref == 'refs/heads/main')  && (github.event_name == 'push')  
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v2   
        with:
          ref: develop   
      - uses: luiscajl/next-maven-snapshot@main
  notification:
    needs: [deploy-release, next-snapshot]
    runs-on: ubuntu-latest  
    steps:     
    - name: Send telegram message
      if: ${{ failure() }}
      uses: xinthink/action-telegram@v1
      with:
        botToken: ${{ secrets.TELEGRAM_TOKEN }}
        chatId: ${{ secrets.TELEGRAM_TO }}
        jobStatus: ${{ job.status }}         
        